from __future__ import annotations

from typing import Any, Protocol

DataRecord = dict[str, Any]


class ReviewInsightRepository(Protocol):
    """Persistence boundary used by review, catalog, and analytics services."""

    def list_reviews(self, options: dict[str, Any]) -> dict[str, Any]: ...

    def get_review(self, review_id: str) -> DataRecord | None: ...

    def list_topics(self, options: dict[str, Any]) -> list[DataRecord]: ...

    def get_topic(self, topic_id: str, options: dict[str, Any]) -> DataRecord | None: ...

    def get_topic_reviews(
        self, topic_id: str, options: dict[str, Any]
    ) -> dict[str, Any]: ...

    def list_complaints(self, options: dict[str, Any]) -> list[DataRecord]: ...

    def get_complaint(
        self, complaint_id: str, options: dict[str, Any]
    ) -> DataRecord | None: ...

    def get_complaint_reviews(
        self, complaint_id: str, options: dict[str, Any]
    ) -> dict[str, Any]: ...

    def list_insights(self, options: dict[str, Any]) -> list[DataRecord]: ...

    def get_insight(self, insight_id: str) -> DataRecord | None: ...

    def create_insight(self, insight: DataRecord) -> DataRecord: ...

    def list_products(self) -> list[DataRecord]: ...

    def dashboard_data(self, filters: dict[str, Any]) -> dict[str, Any]: ...

    def model_health_data(self, days: int) -> dict[str, Any]: ...
