import { useState } from 'react'
import { FileText, Download, Loader, CheckCircle, Calendar } from 'lucide-react'

import report1 from '@/assets/icons/report_monthly.png'
import report2 from '@/assets/icons/report_complaints.png'
import report3 from '@/assets/icons/report_topics.png'
import report4 from '@/assets/icons/report_executive.png'

const REPORT_TEMPLATES = [
  {
    id: 'monthly-sentiment',
    title: 'Monthly Sentiment Summary',
    description: 'Comprehensive overview of sentiment trends, score breakdowns, and key shifts over the past 30 days.',
    icon: report1,
    color: '#7C3AED',
    bg: 'rgba(124,58,237,0.08)',
    lastGenerated: '2026-09-30',
  },
  {
    id: 'complaint-report',
    title: 'Complaint Intelligence Report',
    description: 'Detailed breakdown of active complaint clusters, severity distribution, and resolution progress.',
    icon: report2,
    color: '#F43F5E',
    bg: 'rgba(244,63,94,0.08)',
    lastGenerated: '2026-10-01',
  },
  {
    id: 'topic-analysis',
    title: 'Topic Analysis Deep Dive',
    description: 'Emerging and declining topic clusters across product lines with keyword extraction.',
    icon: report3,
    color: '#3B82F6',
    bg: 'rgba(59,130,246,0.08)',
    lastGenerated: '2026-09-28',
  },
  {
    id: 'executive-brief',
    title: 'Executive Brief',
    description: 'High-level KPI summary formatted for stakeholder presentations. One-page overview.',
    icon: report4,
    color: '#10B981',
    bg: 'rgba(16,185,129,0.08)',
    lastGenerated: '2026-10-02',
  },
]

interface GeneratedReport {
  id: string
  title: string
  generatedAt: string
}

export function Reports() {
  const [generating, setGenerating] = useState<string | null>(null)
  const [generated, setGenerated] = useState<Set<string>>(new Set())
  const [history, setHistory] = useState<GeneratedReport[]>([
    { id: 'monthly-sentiment', title: 'Monthly Sentiment Summary', generatedAt: '2026-10-01T10:22:00Z' },
    { id: 'executive-brief', title: 'Executive Brief', generatedAt: '2026-09-30T14:05:00Z' },
  ])

  const handleGenerate = (templateId: string, title: string) => {
    setGenerating(templateId)
    setTimeout(() => {
      setGenerating(null)
      setGenerated(prev => new Set([...prev, templateId]))
      setHistory(prev => [
        { id: templateId, title, generatedAt: new Date().toISOString() },
        ...prev.slice(0, 4),
      ])
    }, 2200)
  }

  const handleDownload = (title: string) => {
    // Simulate PDF download via window.print on a hidden element
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(`
        <html><head><title>${title}</title>
        <style>body{font-family:system-ui;padding:40px;max-width:800px;margin:0 auto}h1{color:#1C1033}p{color:#4B4466}</style>
        </head><body>
        <h1>${title}</h1>
        <p>Generated by ReviewBand Intelligence Platform on ${new Date().toLocaleDateString()}</p>
        <p>This report contains sentiment analysis, topic trends, and complaint intelligence for the selected time period.</p>
        </body></html>
      `)
      printWindow.document.close()
      printWindow.print()
    }
  }

  return (
    <div className="page-section" style={{ paddingBottom: 80 }}>
      <header style={{ marginBottom: 28 }}>
        <h1 style={{ fontSize: 30, fontWeight: 700, color: '#1C1033', letterSpacing: '-0.03em', marginBottom: 6 }}>Reports</h1>
        <p style={{ fontSize: 15, color: '#4B4466' }}>Generate, preview, and export executive briefs and summaries.</p>
      </header>

      {/* Templates */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 20, marginBottom: 32 }}>
        {REPORT_TEMPLATES.map(template => {
          const isGenerating = generating === template.id
          const isDone = generated.has(template.id)
          return (
            <div key={template.id} className="glass-card" style={{ padding: 28, display: 'flex', flexDirection: 'column' }}>
              <div style={{ width: 44, height: 44, borderRadius: 12, background: template.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 16 }}>
                <img src={template.icon} alt="" style={{ width: 26, height: 26, objectFit: 'contain', display: 'block' }} />
              </div>
              <h3 style={{ fontSize: 16, fontWeight: 600, color: '#1C1033', margin: '0 0 8px' }}>{template.title}</h3>
              <p style={{ fontSize: 13, color: '#8B83A3', lineHeight: 1.5, flex: 1, margin: '0 0 16px' }}>{template.description}</p>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#8B83A3', fontSize: 12, marginBottom: 16 }}>
                <Calendar size={12} />
                Last: {new Date(template.lastGenerated).toLocaleDateString()}
              </div>
              <div style={{ display: 'flex', gap: 8 }}>
                <button
                  onClick={() => !isGenerating && !isDone && handleGenerate(template.id, template.title)}
                  disabled={isGenerating}
                  style={{
                    flex: 1, padding: '10px 16px', borderRadius: 8,
                    background: isDone ? 'rgba(16,185,129,0.1)' : `linear-gradient(135deg, ${template.color}, ${template.color}cc)`,
                    border: isDone ? '1px solid rgba(16,185,129,0.3)' : 'none',
                    color: isDone ? '#10B981' : '#fff',
                    fontSize: 13, fontWeight: 600, cursor: isGenerating ? 'wait' : 'pointer',
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6
                  }}
                >
                  {isGenerating ? <><Loader size={14} className="spin" /> Generating...</> :
                   isDone ? <><CheckCircle size={14} /> Generated</> :
                   'Generate Report'}
                </button>
                {isDone && (
                  <button
                    onClick={() => handleDownload(template.title)}
                    style={{
                      padding: '10px 12px', borderRadius: 8,
                      background: 'rgba(255,255,255,0.5)', border: '1px solid rgba(0,0,0,0.08)',
                      cursor: 'pointer', display: 'flex', alignItems: 'center'
                    }}
                  >
                    <Download size={14} style={{ color: '#4B4466' }} />
                  </button>
                )}
              </div>
            </div>
          )
        })}
      </div>

      {/* History */}
      <div className="glass-card" style={{ padding: 24 }}>
        <h2 style={{ fontSize: 16, fontWeight: 600, color: '#1C1033', margin: '0 0 16px' }}>Recent Reports</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {history.map((item, idx) => (
            <div key={idx} className="glass-secondary interactive" style={{ padding: '12px 16px', borderRadius: 10, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <FileText size={16} style={{ color: '#A855F7' }} />
                <span style={{ fontSize: 14, fontWeight: 500, color: '#1C1033' }}>{item.title}</span>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <span style={{ fontSize: 12, color: '#8B83A3' }}>{new Date(item.generatedAt).toLocaleString()}</span>
                <button
                  onClick={() => handleDownload(item.title)}
                  style={{ background: 'none', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', color: '#7C3AED' }}
                >
                  <Download size={14} />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      <style>{`
        .spin { animation: spin 1s linear infinite; }
        @keyframes spin { 100% { transform: rotate(360deg); } }
      `}</style>
    </div>
  )
}
